[sdl]
output=default
fullscreen=false
autolock=false
waitonerror=true

[dosbox]
machine=svga_s3
memsize=64
captures=capture

[cpu]
core=auto
cycles=max

[render]
scaler=normal2x

[mixer]
nosound=false
rate=44100
blocksize=1024
prebuffer=20

[midi]
mpu401=intelligent
mididevice=win32

[sblaster]
sbtype=sbpro2
sbbase=220
irq=7
dma=1
hdma=5
sbmixer=true
oplmode=opl3
oplrate=44100

[gus]
gus=false

[dos]
xms=true
ems=true
umb=true

[autoexec]
imgmount d "D:\Game\VigameV1.0\games\MyRPG\game\Sango2\Sango2.ccd" -t cdrom
mount c "D:\Game\SAN"
SET BLASTER=A220 I7 D1 H5 T6
echo.
echo  ============================================
echo   SANGO II - CAI DAT (INSTALL)
echo  ============================================
echo   1. Chon muc 1 (Sango II) trong menu
echo   2. Lam theo huong dan INST va SETSOUND
echo   3. Sau khi cai xong, chay "Apply Crack.bat"
echo  ============================================
echo.
d:
INSTALL.BAT
