[sdl]
output=default
fullscreen=false
fulldouble=false
autolock=false
waitonerror=true

[dosbox]
machine=svga_s3
memsize=64

[cpu]
core=auto
cycles=max

[render]
scaler=normal2x

[mixer]
nosound=false
rate=44100
blocksize=1024
prebuffer=20

[midi]
mpu401=intelligent
mididevice=win32

[sblaster]
sbtype=sbpro2
sbbase=220
irq=7
dma=1
hdma=5
sbmixer=true
oplmode=opl3
oplrate=44100

[gus]
gus=false

[dos]
xms=true
ems=true
umb=true

[autoexec]
imgmount d "D:\Game\VigameV1.0\games\MyRPG\game\CD-ROM\Sango2.cue" -t cdrom
mount c "D:\Game\SAN"
SET BLASTER=A220 I7 D1 H5 T6
c:
cd \sango2
if not exist san2-vn.exe echo Loi: Chua build ban dich! Chay D:\Game\SAN\repo\scripts\build_vn_release.bat & pause & exit
call go8mb-vn.bat
