[sdl]
output=default
fullscreen=false
autolock=false

[dosbox]
machine=svga_s3
memsize=64

[cpu]
core=auto
cycles=max

[render]
scaler=normal2x

[mixer]
nosound=false
rate=44100

[midi]
mpu401=intelligent
mididevice=win32

[sblaster]
sbtype=sbpro2
sbbase=220
irq=7
dma=1
hdma=5
oplmode=opl3

[cdrom]
cdrom = enable

[dos]
xms=true
ems=true
umb=true

[autoexec]
@echo off
REM *** SUA DUONG DAN CHO DUNG MAY BAN ***
mount c "D:\Game\VigameV1.0\games\MyRPG\game"
SET BLASTER=A220 I7 D1 H5 T6
c:
call launch_syllable.bat
