[sdl]
output=default
waitonerror=true

[dosbox]
machine=svga_s3
memsize=32

[dos]
automount=false
automountall=false

[autoexec]
@echo off
imgmount d "D:\Game\VigameV1.0\games\MyRPG\game\Sango2\Sango2.ccd" -t cdrom
mount c "D:\Game\SAN\_crack\crack_out" -freesize 512
d:
cd \crack
copy *.* c:\ /y
exit
